on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: ./
        env:
          1: "2021-05-01"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}