on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Test
        uses: ./
        env:
          1: "2021-05-01"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}